// Generated by IcedCoffeeScript 108.0.11
(function() {
  var ApplicantController_Individual;

  ApplicantController_Individual = function($scope, $http, GlobalObjectsFactory, ApplicationDataFactory, ApplicationDataService) {
    var vm;
    vm = this;
    vm.globals = GlobalObjectsFactory;
    vm.appData = ApplicationDataFactory;
    vm.states = {
      addOtherName: false,
      mailingAddressSameAsHome: false
    };
    vm.fullName = {};
    vm.newOtherName = {
      firstName: "",
      middleName: "",
      lastName: ""
    };
    vm.otherNames = [];
    vm.fullNameTemplate = {
      firstName: "",
      middleName: "",
      lastName: ""
    };
    vm.addressTemplate = {
      street1: "",
      street2: "",
      city: "",
      state: "",
      zip: ""
    };
    vm.homeAddress = angular.copy(vm.addressTemplate);
    vm.homeAddress.street1 = "E-503, Gopalanand";
    vm.homeAddress.street2 = "Chandkheda";
    vm.homeAddress.city = "Ahmedabad";
    vm.homeAddress.state = "NJ";
    vm.homeAddress.zip = "38254";
    vm.mailingAddressSameAsHome = "false";
    vm.phoneNumberTemplate = {
      number: "",
      isMobile: false
    };
    vm.primaryPhone = angular.copy(vm.phoneNumberTemplate);
    vm.secondaryPhone = angular.copy(vm.phoneNumberTemplate);
    vm.primaryEmail = "";
    vm.secondaryEmail = "";
    vm.haveEmail = true;
    vm.haveWebsite = 0;
    vm.website = "www.website.com";
    vm.saveOtherName = function() {
      console.log(vm.newOtherName);
      vm.otherNames.push(vm.newOtherName);
      return vm.newOtherName = angular.copy(vm.fullNameTemplate);
    };
    vm.saveApplicant = function() {
      var home;
      home = vm.appData.Applicant.HomeAddress;
      home.BeginDate = new Date();
      home.EndDate = new Date();
      home.IndividualId = parseInt(sessionStorage.IndividualId);
      home.AddressTypeId = 2;
      home.AddressStatusId = 9;
      ApplicationDataService.address.save.individualAddress(home).then(function(response) {
        return console.log(response, "Saved Home Address");
      });
      window.location.hash = "#" + "/identification";
      return IndividualSectionManager.changeSelection($("#liSection2"));
    };
    vm.thisObj = function(obj, evt) {
      return console.log(evt);
    };
  };

  angular.module('IndividualApp').controller('applicantCtrl', ApplicantController_Individual);

  ApplicantController_Individual.$inject = ['$scope', '$http', 'GlobalObjectsFactory', 'ApplicationDataFactory', 'ApplicationDataService'];

}).call(this);
