// Generated by IcedCoffeeScript 108.0.11
(function() {
  var ApplicantController_Individual;

  ApplicantController_Individual = function($scope, $http, GlobalObjectsFactory, ApplicationDataFactory, ApplicationDataService) {
    var vm;
    vm = this;
    vm.globals = GlobalObjectsFactory;
    vm.appData = ApplicationDataFactory;
    vm.states = {
      addOtherName: false,
      mailingAddressSameAsHome: false
    };
    vm.fullName = {};
    vm.newOtherName = {
      firstName: "",
      middleName: "",
      lastName: ""
    };
    vm.otherNames = [];
    vm.fullNameTemplate = {
      firstName: "",
      middleName: "",
      lastName: ""
    };
    vm.mailingAddressSameAsHome = "false";
    vm.phoneNumberTemplate = {
      number: "",
      isMobile: false
    };
    vm.primaryPhone = angular.copy(vm.phoneNumberTemplate);
    vm.secondaryPhone = angular.copy(vm.phoneNumberTemplate);
    vm.primaryPhone.isMobile = true;
    vm.primaryEmail = "";
    vm.secondaryEmail = "";
    vm.haveEmail = true;
    vm.haveWebsite = 0;
    vm.website = "www.website.com";
    vm.saveOtherName = function() {
      console.log(vm.newOtherName);
      vm.otherNames.push(vm.newOtherName);
      return vm.newOtherName = angular.copy(vm.fullNameTemplate);
    };
    vm.saveApplicant = function() {
      var home;
      home = vm.appData.Applicant.HomeAddress;
      home.BeginDate = new Date();
      home.EndDate = new Date();
      home.IndividualId = parseInt(sessionStorage.IndividualId);
      home.AddressTypeId = 2;
      home.AddressStatusId = 9;
      ApplicationDataService.address.save.individualAddress(home).then(function(response) {
        return console.log(response, "Saved Home Address");
      });
      ApplicationDataService.contact.save(vm.appData.Applicant.PrimaryPhone).then(function(response) {
        return console.log(response, "Saved Primary Phone");
      });
      if (vm.appData.Applicant.SecondaryPhone.ContactInfo !== "") {
        ApplicationDataService.contact.save(vm.appData.Applicant.SecondaryPhone).then(function(response) {
          return console.log(response, "Saved Secondary Phone");
        });
      }
      if (vm.appData.Applicant.PrimaryEmail.ContactInfo !== "") {
        ApplicationDataService.contact.save(vm.appData.Applicant.PrimaryEmail).then(function(response) {
          return console.log(response, "Saved Primary Email");
        });
      }
      if (vm.appData.Applicant.SecondaryEmail.ContactInfo !== "") {
        ApplicationDataService.contact.save(vm.appData.Applicant.SecondaryEmail).then(function(response) {
          return console.log(response, "Saved Secondary Email");
        });
      }
      if (vm.appData.Applicant.Website.ContactInfo !== "") {
        ApplicationDataService.contact.save(vm.appData.Applicant.Website).then(function(response) {
          return console.log(response, "Saved Website");
        });
      }
      window.location.hash = "#" + "/identification";
      return IndividualSectionManager.changeSelection($("#liSection2"));
    };
    vm.thisObj = function(obj, evt) {
      return console.log(evt);
    };
  };

  angular.module('IndividualApp').controller('applicantCtrl', ApplicantController_Individual);

  ApplicantController_Individual.$inject = ['$scope', '$http', 'GlobalObjectsFactory', 'ApplicationDataFactory', 'ApplicationDataService'];

}).call(this);
