// Generated by IcedCoffeeScript 108.0.11
(function() {
  var EducationController;

  EducationController = function($scope, GlobalDataFactory, ApplicationDataFactory) {
    var vm;
    vm = this;
    vm.appData = ApplicationDataFactory;
    vm.states = {
      AddingApprovedSchool: false,
      AddingNonApprovedSchool: false,
      AddingSchoolOutsideCA: false,
      AddingExam: false
    };
    vm.save = function() {
      window.location.hash = "#" + "/workinformation";
      return IndividualSectionManager.changeSelection($("#liSection5"));
    };
  };

  angular.module('IndividualApp').controller('educationCtrl', EducationController);

  EducationController.$inject = ['$scope', 'GlobalObjectsFactory', 'ApplicationDataFactory'];

}).call(this);
