// Generated by IcedCoffeeScript 108.0.11
(function() {
  var HistoryController;

  HistoryController = function($scope, GlobalDataFactory, ApplicationDataFactory) {
    var vm;
    vm = this;
    vm.appData = ApplicationDataFactory;
    vm.states = {};
    vm.save = function() {
      window.location.hash = "#" + "/affidavit";
      return IndividualSectionManager.changeSelection($("#liSection7"));
    };
  };

  angular.module('IndividualApp').controller('historyCtrl', HistoryController);

  HistoryController.$inject = ['$scope', 'GlobalObjectsFactory', 'ApplicationDataFactory'];

}).call(this);
