// Generated by IcedCoffeeScript 108.0.11
(function() {
  var IdentificationController;

  IdentificationController = function($scope, GlobalDataFactory, ApplicationDataFactory) {
    var vm;
    vm = this;
    vm.appData = ApplicationDataFactory;
    vm.save = function() {
      window.location.hash = "#" + "/licensure";
      return IndividualSectionManager.changeSelection($("#liSection3"));
    };
  };

  angular.module('IndividualApp').controller('identificationCtrl', IdentificationController);

  IdentificationController.$inject = ['$scope', 'GlobalObjectsFactory', 'ApplicationDataFactory'];

}).call(this);
