// Generated by IcedCoffeeScript 108.0.11
(function() {
  var InstructionController;

  InstructionController = function($scope) {
    var vm;
    vm = this;
    vm.scope = $scope;
    $(".testDiv").each(function(i, e) {
      return e.modelValue = "Div " + i;
    });
    vm.myValue = "Test Value 1";
    this.myfunction = function(obj) {
      console.log(obj);
    };
    this.getValue = function(obj) {
      console.log(obj);
      return console.log(vm.scope);
    };
  };

  angular.module('IndividualApp').controller('instructionCtrl', InstructionController);

  InstructionController.$inject = ['$scope'];

}).call(this);
