// Generated by IcedCoffeeScript 108.0.11
(function() {
  var LicensureController;

  LicensureController = function($scope, GlobalDataFactory, ApplicationDataFactory) {
    var vm;
    vm = this;
    vm.appData = ApplicationDataFactory;
    vm.states = {
      addingNewLicense: false,
      editingLicense: false
    };
    vm.save = function() {
      window.location.hash = "#" + "/education";
      return IndividualSectionManager.changeSelection($("#liSection4"));
    };
  };

  angular.module('IndividualApp').controller('licensureCtrl', LicensureController);

  LicensureController.$inject = ['$scope', 'GlobalObjectsFactory', 'ApplicationDataFactory'];

}).call(this);
