// Generated by IcedCoffeeScript 108.0.11
(function() {
  var MainController_Individual;

  MainController_Individual = function($scope, $http, GlobalObjectsFactory) {
    var vm;
    vm = this;
    vm.testValue = "My Main Test Value";
    vm.globals = GlobalObjectsFactory;
    console.log(vm.globals.countries);
    vm.ApplicationModel = {};
  };

  angular.module('IndividualApp').controller('mainCtrl', MainController_Individual);

  MainController_Individual.$inject = ['$scope', '$http', 'GlobalObjectsFactory'];

}).call(this);
