// Generated by IcedCoffeeScript 108.0.11
(function() {
  var WorkInformationController;

  WorkInformationController = function($scope, GlobalDataFactory, ApplicationDataFactory) {
    var vm;
    vm = this;
    vm.appData = ApplicationDataFactory;
    vm.states = {
      AddingCurrentPlaceOfWork: false,
      AddingProspectiveEmployer: false,
      AddingPreviousWorkLocations: false,
      AddingPreviousResidentialLocations: false
    };
    vm.save = function() {
      window.location.hash = "#" + "/history";
      return IndividualSectionManager.changeSelection($("#liSection6"));
    };
  };

  angular.module('IndividualApp').controller('workCtrl', WorkInformationController);

  WorkInformationController.$inject = ['$scope', 'GlobalObjectsFactory', 'ApplicationDataFactory'];

}).call(this);
