// Generated by IcedCoffeeScript 108.0.11
(function() {
  var app;

  app = angular.module('IndividualApp');

  app.directive('convertToNumber', function() {
    return {
      require: 'ngModel',
      link: function(scope, element, attrs, ngModel) {
        ngModel.$parsers.push(function(val) {
          return parseInt(val, 10);
        });
        return ngModel.$formatters.push(function(val) {
          return '' + val;
        });
      }
    };
  });

}).call(this);
