// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('IndividualApp', ['ngRoute']).config([
    '$locationProvider', '$routeProvider', function($locationProvider, $routeProvider) {
      return $("#menu-w-licensure li").each(function() {
        return $routeProvider.when($(this).data('hash'), {
          templateUrl: 'LoadSection/' + $(this).data('section'),
          controller: $(this).data('controller'),
          reloadOnSearch: false
        });
      });
    }
  ]);

}).call(this);
