// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('IndividualApp').run(function($rootScope, $http, GlobalObjectsService, GlobalObjectsFactory, ApplicationDataService, ApplicationDataFactory, $q) {
    console.log("Running App");
    ShowLoader();
    GlobalObjectsService.getAllCountries().then(function(response) {
      GlobalObjectsFactory.countries = response.data.Country;
      console.log(GlobalObjectsFactory);
    });
    ApplicationDataService.startUp(ApplicationDataFactory);
  });

}).call(this);
