// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('IndividualApp').run(function($rootScope, $http, GlobalObjectsService, GlobalObjectsFactory, ApplicationDataService, ApplicationDataFactory, ObjectTemplateFactory, $q) {
    var globalQ, lookupQ;
    console.log("Running App");
    ShowLoader();
    $rootScope.$on('$routeChangeStart', function(event, toState, toParams, fromState, fromParams) {
      console.log("Loading...");
      return ShowLoader();
    });
    $rootScope.$on('$routeChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
      console.log("Done Loading...");
      return HideLoader();
    });
    lookupQ = [];
    lookupQ.push(GlobalObjectsService.lookup.getAllLookupTypes());
    lookupQ.push(GlobalObjectsService.lookup.getLookupByTypeId("35", "HairColorTypes"));
    lookupQ.push(GlobalObjectsService.lookup.getLookupByTypeId("36", "EyeColorTypes"));
    lookupQ.push(GlobalObjectsService.lookup.getLookupByTypeId("37", "GenderTypes"));
    globalQ = [];
    globalQ.push(GlobalObjectsService.typevalues.get.addresTypes());
    globalQ.push(GlobalObjectsService.getAllCountries());
    $q.all(lookupQ).then(function(data) {
      console.log(data);
      GlobalObjectsFactory.lookupTypes = data[0].data.LookupType;
      GlobalObjectsFactory.hairColorTypes = data[1].data.Lookup;
      GlobalObjectsFactory.eyeColorTypes = data[2].data.Lookup;
      GlobalObjectsFactory.genderTypes = data[3].data.Lookup;
      return $q.all(globalQ).then(function(data) {
        GlobalObjectsFactory.addressTypes = data[0].data.AddressTypeGetList;
        GlobalObjectsFactory.countries = data[1].data.Country;
        console.log(GlobalObjectsFactory);
        ApplicationDataService.startUp(ApplicationDataFactory);
      });
    });
  });

}).call(this);
