// Generated by IcedCoffeeScript 108.0.11
(function() {
  var app;

  app = angular.module('IndividualApp');

  app.filter('contactByTypeId', function() {
    return function(input, id) {
      var item, _i, _len;
      for (_i = 0, _len = input.length; _i < _len; _i++) {
        item = input[_i];
        if (item.ContactTypeId === id) {
          return item;
        }
      }
      return null;
    };
  });

}).call(this);
