// Generated by IcedCoffeeScript 108.0.11
(function() {
  var ApplicationDataService;

  ApplicationDataService = function($http, $q, $rootScope, ObjectTemplateFactory, $filter) {
    var vm;
    vm = this;
    vm.baseUrl = "http://ws.camtc.inlumon.com/api";
    vm.key = sessionStorage.Key != null ? sessionStorage.Key : "";
    vm.factory = {};
    return vm.service = {
      startUp: function(factory) {
        vm.factory = factory;
        vm.service.getIndividual(sessionStorage.IndividualId).then(function(response) {
          console.log("Individual", response.data.IndividualResponse);
          if (response.data.IndividualResponse.length === 1) {
            return factory.Individual = response.data.IndividualResponse[0];
          }
        });
        vm.service.getIndividualName(sessionStorage.IndividualId).then(function(response) {
          return factory.IndividualName = response.data.IndividualNameResponse[0];
        });
        vm.service.getIndividualAddress(sessionStorage.IndividualId).then(function(response) {
          var address, _i, _len, _ref, _results;
          HideLoader();
          console.log("Address", response.data);
          if (response.data.IndividualAddressResponse.length > 0) {
            _ref = response.data.IndividualAddressResponse;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              address = _ref[_i];
              if (address.AddressTypeId === 2) {
                _results.push(factory.Applicant.HomeAddress = address);
              } else {
                _results.push(void 0);
              }
            }
            return _results;
          } else {
            factory.Applicant.HomeAddress = angular.copy(ObjectTemplateFactory.address.newAddress);
            return factory.Applicant.HomeAddress.AddressTypeId = 2;
          }
        });
        return vm.service.contact.get.all(sessionStorage.IndividualId).then(function(response) {
          var primaryEmail, primaryPhone, secEmail, secPhone, website;
          console.log("Contacts", response.data);
          primaryPhone = $filter('contactByTypeId')(response.data.IndividualContactResponse, 6);
          secPhone = $filter('contactByTypeId')(response.data.IndividualContactResponse, 7);
          primaryEmail = $filter('contactByTypeId')(response.data.IndividualContactResponse, 18);
          secEmail = $filter('contactByTypeId')(response.data.IndividualContactResponse, 19);
          website = $filter('contactByTypeId')(response.data.IndividualContactResponse, 17);
          if (primaryPhone === null) {
            factory.Applicant.PrimaryPhone = angular.copy(ObjectTemplateFactory.contact.newContact);
            factory.Applicant.PrimaryPhone.ContactTypeId = 6;
            factory.Applicant.PrimaryPhone.ContactInfo = "";
            factory.Applicant.PrimaryPhone.IndividualId = parseInt(sessionStorage.IndividualId);
          } else {
            primaryPhone.IsActive = true;
            factory.Applicant.PrimaryPhone = primaryPhone;
            console.log(primaryPhone);
          }
          if (secPhone === null) {
            factory.Applicant.SecondaryPhone = angular.copy(ObjectTemplateFactory.contact.newContact);
            factory.Applicant.SecondaryPhone.ContactTypeId = 7;
            factory.Applicant.SecondaryPhone.ContactInfo = "";
            factory.Applicant.SecondaryPhone.IndividualId = parseInt(sessionStorage.IndividualId);
          } else {
            secPhone.IsActive = true;
            factory.Applicant.SecondaryPhone = secPhone;
          }
          if (primaryEmail === null) {
            factory.Applicant.PrimaryEmail = angular.copy(ObjectTemplateFactory.contact.newContact);
            factory.Applicant.PrimaryEmail.ContactTypeId = 18;
            factory.Applicant.PrimaryEmail.ContactInfo = "";
            factory.Applicant.PrimaryEmail.IndividualId = parseInt(sessionStorage.IndividualId);
          } else {
            primaryEmail.IsActive = true;
            factory.Applicant.PrimaryEmail = primaryEmail;
          }
          if (secEmail === null) {
            factory.Applicant.SecondaryEmail = angular.copy(ObjectTemplateFactory.contact.newContact);
            factory.Applicant.SecondaryEmail.ContactTypeId = 19;
            factory.Applicant.SecondaryEmail.ContactInfo = "";
            factory.Applicant.SecondaryEmail.IndividualId = parseInt(sessionStorage.IndividualId);
          } else {
            secEmail.IsActive = true;
            factory.Applicant.SecondaryEmail = secEmail;
          }
          if (website === null) {
            factory.Applicant.Website = angular.copy(ObjectTemplateFactory.contact.newContact);
            factory.Applicant.Website.ContactTypeId = 17;
            factory.Applicant.Website.ContactInfo = "";
            return factory.Applicant.Website.IndividualId = parseInt(sessionStorage.IndividualId);
          } else {
            website.IsActive = true;
            return factory.Applicant.Website = website;
          }
        });
      },
      getIndividualName: function(ind_id) {
        return $http.get(vm.baseUrl + "/Individual/IndividualNameBYIndividualId/" + vm.key + "?IndividualId=" + ind_id);
      },
      getIndividualAddress: function(ind_id) {
        return $http.get(vm.baseUrl + "/Individual/IndividualAddressBYIndividualId/" + vm.key + "?IndividualId=" + ind_id);
      },
      getIndividual: function(ind_id) {
        return $http.get(vm.baseUrl + "/Individual/IndividualOnlyBYIndividualId/" + vm.key + "?IndividualId=" + ind_id);
      },
      individual: {
        save: function(individual) {
          return $http.post(vm.baseUrl + "/Individual/IndividualSave/" + vm.key, individual);
        }
      },
      address: {
        get: {
          allByIndividualId: function(ind_id) {
            return $http.get(vm.baseUrl + "/Individual/IndividualAddressBYIndividualId/" + vm.key + "?IndividualId=" + ind_id);
          },
          byId: function(addressId) {
            return console.log(addressId);
          }
        },
        save: {
          individualAddress: function(newAddress) {
            return $http.post(vm.baseUrl + "/Individual/IndividualAddressSave/" + vm.key, newAddress);
          }
        }
      },
      contact: {
        get: {
          all: function(ind_id) {
            return $http.get(vm.baseUrl + "/Individual/IndividualContactBYIndividualId/" + vm.key + "?IndividualId=" + ind_id);
          }
        },
        save: function(contact) {
          return $http.post(vm.baseUrl + "/Individual/IndividualContactSave/" + vm.key, contact);
        }
      }
    };
  };

  angular.module('IndividualApp').service("ApplicationDataService", ApplicationDataService);

  ApplicationDataService.$inject = ['$http', '$q', '$rootScope', 'ObjectTemplateFactory', '$filter'];

}).call(this);
