// Generated by IcedCoffeeScript 108.0.11
(function() {
  var GlobalObjectsService;

  GlobalObjectsService = function($http) {
    var vm;
    vm = this;
    vm.baseUrl = "http://localhost:1530/api";
    vm.key = sessionStorage.Key != null ? sessionStorage.Key : "";
    return vm.objects = {
      getAllCountries: function() {
        return $http.get(vm.baseUrl + "/Country/CountryGetAll/" + vm.key);
      }
    };
  };

  angular.module('IndividualApp').service("GlobalObjectsService", GlobalObjectsService);

  GlobalObjectsService.$inject = ['$http'];

}).call(this);
