// Generated by IcedCoffeeScript 108.0.11
(function() {
  var GlobalObjectsFactory;

  GlobalObjectsFactory = function(GlobalObjectsService) {
    var vm;
    vm = this;
    return vm.objects = {
      countries: [],
      getAllCountries: function() {
        if (this.countries.length > 0) {
          return this.countries;
        } else {
          GlobalObjectsService.getAllCountries().success(function(response) {
            console.log(response);
            vm.objects.countries = response.Country;
            return vm.objects.countries;
          });
        }
      },
      getAllStatesByCountry: function(country) {
        return console.log(country);
      },
      applicant: {
        fullName: {
          firstName: "NancyGlobal",
          middleName: "E",
          lastName: "Blachly"
        }
      }
    };
  };

  angular.module('IndividualApp').factory("GlobalObjectsFactory", GlobalObjectsFactory);

  GlobalObjectsFactory.$inject = ['GlobalObjectsService'];

}).call(this);
